---

# consul start
- hosts: hosts-consul-server
  serial: 1
  roles:
    - {role: service, state: started, name: vitam-consul}

- hosts: vitam
  roles:
    - {role: service, state: started, name: vitam-consul}
    
# log-central start
- hosts: hosts-elasticsearch-log
  roles:
    - {role: service, state: started, name: vitam-elasticsearch-log, port_check: "{{elasticsearch_log_tcp_port}}"}

- hosts: hosts-log-server
  roles:
    - {role: service, state: started, name: logstash, port_check: "{{vitam_logstash_port}}"}
    - {role: service, state: started, name: kibana, port_check: "{{vitam_kibana_port}}"}

# Databases start
- hosts: mongoc
  roles:
    - { role: service, state: started, name: vitam-mongoc, port_check: "{{mongoc_port}}" }

- hosts: mongod
  roles:
    - { role: service, state: started, name: vitam-mongod, port_check: "{{mongod_port}}" }

- hosts: mongos
  roles:
    - { role: service, state: started, name: vitam-mongos, port_check: "{{mongos_port}}" }

- hosts: hosts-mongoclient
  roles:
    - {role: service, state: started, name: vitam-mongoclient, port_check: "{{mongoclientPort}}"}

- hosts: hosts-elasticsearch-data
  roles:
    - { role: service, state: started, name: vitam-elasticsearch-data, port_check: "{{elasticsearch_data_tcp_port}}" }


# Vitam apps start

- hosts: hosts-storage-offer-default
  roles:
    - {role: service, state: started, name: vitam-storage-offer-default, port_check: "{{vitam_storageofferdefault_port_https}}" }

- hosts: hosts-storage-engine
  roles:
    - {role: service, state: started, name: vitam-storage, port_check: "{{vitam_storageengine_port}}"}

- hosts: hosts-metadata
  roles:
    - {role: service, state: started, name: vitam-metadata, port_check: "{{vitam_metadata_port}}"}

- hosts: hosts-workspace
  roles:
    - {role: service, state: started, name: vitam-workspace, port_check: "{{vitam_workspace_port}}"}

- hosts: hosts-logbook
  roles:
    - {role: service, state: started, name: vitam-logbook, port_check: "{{vitam_logbook_port}}"}

- hosts: hosts-functional-administration
  roles:
    - {role: service, state: started, name: vitam-functional-administration, port_check: "{{vitam_functional_administration_port}}"}

- hosts: hosts-processing
  roles:
    - {role: service, state: started, name: vitam-processing, port_check: "{{vitam_processing_port}}"}

- hosts: hosts-worker
  roles:
    - {role: service, state: started, name: vitam-siegfried}
    - {role: service, state: started, name: vitam-worker, port_check: "{{vitam_worker_port}}"}

- hosts: hosts-access-internal
  roles:
    - {role: service, state: started, name: vitam-access-internal, port_check: "{{vitam_accessinternal_port}}"}

- hosts: hosts-access-external
  roles:
    - {role: service, state: started, name: vitam-access-external, port_check: "{{vitam_accessexternal_port_https}}"}

- hosts: hosts-ingest-internal
  roles:
    - {role: service, state: started, name: vitam-ingest-internal, port_check: "{{vitam_ingestinternal_port}}"}

- hosts: hosts-ingest-external
  roles:
    - {role: service, state: started, name: vitam-siegfried}
    - {role: service, state: started, name: vitam-ingest-external, port_check: "{{vitam_ingestexternal_port_https}}"}

- hosts: hosts-ihm-demo
  roles:
    - {role: service, state: started, name: vitam-ihm-demo, port_check: "{{vitam_ihm_demo_port}}"}
