---

- hosts: hosts-ingest-external
  roles:
    - {role: vitam_autotest, vitam_component: ingest-external, port: "{{vitam_ingestexternal_port_https}}", protocol: "https" }

- hosts: hosts-ingest-internal
  roles:
    - {role: vitam_autotest, vitam_component: ingest-internal, port: "{{vitam_ingestinternal_port}}" }

- hosts: hosts-acces-external
  roles:
    - {role: vitam_autotest, vitam_component: access-external, port: "{{vitam_accessexternal_port_https}}", protocol: "https" }

- hosts: hosts-access-internal
  roles:
    - {role: vitam_autotest, vitam_component: access-internal, port: "{{vitam_accessinternal_port}}" }

- hosts: hosts-worker
  roles:
    - {role: vitam_autotest, vitam_component: worker, port: "{{vitam_worker_port}}" }

- hosts: hosts-processing
  roles:
    - {role: vitam_autotest, vitam_component: processing, port: "{{vitam_processing_port}}" }

- hosts: hosts-workspace
  roles:
    - {role: vitam_autotest, vitam_component: workspace, port: "{{vitam_workspace_port}}" }

- hosts: hosts-functional-administration
  roles:
    - {role: vitam_autotest, vitam_component: functional-administration, port: "{{vitam_functional_administration_port}}" }

- hosts: hosts-logbook
  any_errors_fatal: false
  roles:
    - {role: vitam_autotest, vitam_component: logbook, port: "{{vitam_logbook_port}}" }

- hosts: hosts-metadata
  roles:
    - {role: vitam_autotest, vitam_component: metadata, port: "{{vitam_metadata_port}}" }

- hosts: hosts-storage-engine
  roles:
    - {role: vitam_autotest, vitam_component: storage, port: "{{vitam_storageengine_port}}" }

- hosts: hosts-storage-offer-default
  roles:
    - {role: vitam_autotest, vitam_component: storage-offer-default, port: "{{vitam_storageofferdefault_port_https}}", protocol: "https" }
