---

# Vitam apps stop

- hosts: hosts-ihm-demo
  roles:
    - {role: service, state: stopped, name: vitam-ihm-demo}

- hosts: hosts-ingest-external
  roles:
    - {role: service, state: stopped, name: vitam-ingest-external}
    - {role: service, state: stopped, name: vitam-siegfried}

- hosts: hosts-ingest-internal
  roles:
    - {role: service, state: stopped, name: vitam-ingest-internal}

- hosts: hosts-access-external
  roles:
    - {role: service, state: stopped, name: vitam-access-external}

- hosts: hosts-access-internal
  roles:
    - {role: service, state: stopped, name: vitam-access-internal}

- hosts: hosts-worker
  roles:
    - {role: service, state: stopped, name: vitam-worker}
    - {role: service, state: stopped, name: vitam-siegfried}

- hosts: hosts-processing
  roles:
    - {role: service, state: stopped, name: vitam-processing}

- hosts: hosts-workspace
  roles:
    - {role: service, state: stopped, name: vitam-workspace}

- hosts: hosts-functional-administration
  roles:
    - {role: service, state: stopped, name: vitam-functional-administration}

- hosts: hosts-logbook
  roles:
    - {role: service, state: stopped, name: vitam-logbook}

- hosts: hosts-metadata
  roles:
    - {role: service, state: stopped, name: vitam-metadata}

- hosts: hosts-storage-engine
  roles:
    - {role: service, state: stopped, name: vitam-storage}

- hosts: hosts-storage-offer-default
  roles:
    - {role: service, state: stopped, name: vitam-storage-offer-default}

- hosts: hosts-mongoclient
  roles:
    - {role: service, state: stopped, name: vitam-mongoclient}

# Databases stop
- hosts: mongos
  roles:
    - {role: service, state: stopped, name: vitam-mongos}

- hosts: mongod
  roles:
    - {role: service, state: stopped, name: vitam-mongod}

- hosts: mongoc
  roles:
    - {role: service, state: stopped, name: vitam-mongoc}

- hosts: hosts-elasticsearch-data
  roles:
    - {role: service, state: stopped, name: vitam-elasticsearch-data}

# log-central stop
- hosts: hosts-log-server
  roles:
    - {role: service, state: stopped, name: kibana}
    - {role: service, state: stopped, name: logstash}

- hosts: hosts-elasticsearch-log
  roles:
    - {role: service, state: stopped, name: vitam-elasticsearch-log}

- hosts: vitam
  roles:
    - {role: service, state: stopped, name: vitam-consul}

# consul stop
- hosts: hosts-consul-server
  serial: 1
  roles:
    - {role: service, state: stopped, name: vitam-consul}
