---
# tasks file for vitam_autotest
- name: check autotest for {{vitam_component}} component
  uri:
    url: '{{protocol}}://{{inventory_hostname}}:{{port}}/admin/v1/autotest'
    method: GET
    status_code: 200
    validate_certs: no
    return_content: yes
  register: response
  ignore_errors: true

# commented as all components are not yet with autotest
# - action: fail
#   when: response | failed


- debug: var=(response.content|from_json)
  when: response | succeeded
