---
# tasks file for clone-tests
- block: 
  - name: get repo for git lfs for CentOS
    copy:
      src: gitlfs-centos7.repo
      dest: /etc/yum.repos.d/github_git-lfs.repo
      owner: root
      group: root
      mode: 0640

  when: (ansible_distribution == "CentOS" )

- block:
  - name: get repo for git lfs for Debian
    copy: 
      src: gitlfs-debian8.list
      dest: /etc/apt/sources.list.d/github_git-lfs.list
      owner: root
      group: root
      mode: 0640

  - name: install package on Debian
    package:
      name: apt-transport-https
      state: latest

  - name: add GPG key
    shell: curl -L "https://packagecloud.io/github/git-lfs/gpgkey" 2> /dev/null | apt-key add -

  - name: update apt cache
    shell: apt-get update
  
  when: (ansible_distribution == "Debian" )

- name: install git-lfs
  package:
    name: git-lfs
    state: latest

# SYSTEM WIDE ? sinon, lancer en tant que vitam
- name: initialize git lfs
  shell: git lfs install

- name: ensure subdir exist
  file:
    path: "{{vitam_folder_root}}/data/ihm-recette/test-data/system"
    state: directory
    owner: "{{ vitam_user}}"
    group: "{{ vitam_group }}"
    mode: "{{ vitam_folder_permission }}"

- name: create git repo
  shell: git clone --no-checkout {{vitam_tests_gitrepo_url}} .
  become_user: "{{vitam_user}}"
  environment:
    http_proxy: "{{ http_proxy_environnement }}"
  args:
    chdir: /vitam/data/ihm-recette/test-data/system/
    creates: /vitam/data/ihm-recette/test-data/system/.git/

- name: store auth
  shell: git config credential.helper 'store --file=/vitam/data/ihm-recette/test-data/system/.git/.git-credentials'
  become_user: "{{vitam_user}}"
  args:
    chdir: /vitam/data/ihm-recette/test-data/system/

- name: copy git-credentials
  template:
    src: git-credentials.j2
    dest: /vitam/data/ihm-recette/test-data/system/.git/.git-credentials
    owner: "{{ vitam_user }}"
    group: "{{ vitam_group }}"
    mode: "{{ vitam_conf_permission }}"
  when: vitam_gitlab_itest_login is defined


# cf. https://help.github.com/articles/caching-your-github-password-in-git/
# and https://git-scm.com/docs/git-credential-cache
# - name: init cache for git
#   shell: git config credential.helper 'store --timeout=3600 --socket=/vitam/data/ihm-recette/test-data/system/.git-credential-cache/socket'
#   become_user: "{{vitam_user}}"
#   args:
#     chdir: /vitam/data/ihm-recette/test-data/system/  

# - name: init cache for git
#   shell: git config credential.helper 'cache --timeout=3600 --socket=/vitam/data/ihm-recette/test-data/system/.git-credential-cache/socket'
#   become_user: "{{vitam_user}}"
#   args:
#     chdir: /vitam/data/ihm-recette/test-data/system/

- name: ensure git repo is clean on current branch
  shell: git clean -fd
  become_user: "{{vitam_user}}"
  environment:
    http_proxy: "{{ http_proxy_environnement }}"
  args:
    chdir: /vitam/data/ihm-recette/test-data/system/

- name: check whether data are already downloaded from git lfs
  stat:
      path: /vitam/data/ihm-recette/test-data/system/data/
  register: git_pulled

- name: get all branches from git repo
  shell: git fetch
  become_user: "{{vitam_user}}"
  environment:
    http_proxy: "{{ http_proxy_environnement }}"
  args:
    chdir: /vitam/data/ihm-recette/test-data/system/

# KWA introduce branch variable
- name: checkout branch
  shell: git checkout {{ vitam_tests_branch }}
  become_user: "{{vitam_user}}"
  environment:
    http_proxy: "{{ http_proxy_environnement }}"
  args:
    chdir: /vitam/data/ihm-recette/test-data/system/
#    creates: /vitam/data/ihm-recette/test-data/system/data/
# Et les droits sur les fichiers ???

- name: rebase documents under git lfs
  shell: git rebase
  become_user: "{{vitam_user}}"
  environment:
    http_proxy: "{{ http_proxy_environnement }}"
  args:
    chdir: /vitam/data/ihm-recette/test-data/system/
  when: (git_pulled.stat.exists) and (git_pulled.stat.isdir is defined) and (git_pulled.stat.isdir)