---

# Vitam solution deployment
- hosts: vitam
  roles:
    - topbeat

- hosts: vitam
  roles:
     - {role: packetbeat, when: "ansible_virtualization_type != 'docker'"}

- hosts: vitam
  roles:
    - vitam_browser

- hosts: hosts-mongo-express
  roles:
    - {role: mongo-express, when: "ansible_virtualization_type != 'docker'"}

- hosts: elasticsearch
  roles:
    - {role: elasticsearch-head}

- hosts: library
  roles:
    - {role: vitam, vitam_component: library, java_args: /vitam/conf/library/library.conf, port_http: "{{vitam_library_port}}", secret_platform: "false" }

- include: ihm-recette.yml

- hosts: reverse
  roles:
    - reverse
