---
# handlers file for common
- name: reload consul configuration
  service:
    name: vitam-consul
    state: reloaded

- name: restart service
  service:
    name: "vitam-{{ vitam_component }}"
    state: restarted
