---

# Install mongodb-org (needed by vitam-mongo* packages)
# and then disable the mongod service as it may start listening on 27017 port which is needed by vitam-mongos
- name: Install mongodb-org package
  package:
    name: mongodb-org
    state: latest

- name: Disable mongodb default service
  service:
    name: mongod
    state: stopped
    enabled: no

### System tuning best practices ####

# next steps in order to disable Transparent HugePages
# cf https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/

- name: Check if tuned is installed
  stat:
    path: /usr/lib/systemd/system/tuned.service
  register: tuned_service_status
  when: ansible_distribution == "CentOS"

- name: Check if tuned is installed
  stat:
    path: /lib/systemd/system/tuned.service
  register: tuned_service_status
  when: ansible_distribution == "Debian"

- set_fact: status_tuned_present="{{tuned_service_status.stat.exists}}"
  when: tuned_service_status.changed

- name: create the tuned conf directory
  file:
    path: "/etc/tuned/no-thp"
    state: directory
    owner: root
    mode: "{{vitam_folder_permission}}"
  when: status_tuned_present

- name: add the tuned conf file
  copy:
    src: tuned.conf
    dest: /etc/tuned/no-thp/tuned.conf
    owner: root
    mode: "{{vitam_conf_permission}}"
  when: status_tuned_present

- name: enable the new tuned profile
  command: tuned-adm profile no-thp
  when: status_tuned_present

- name: restart tuned
  service:
    name: tuned
    state: restarted
  when: status_tuned_present

- name: add systemd service unit to disable THP
  copy:
    src: disable_transparent_hugepages.service
    dest: /usr/lib/systemd/system/disable_transparent_hugepages.service
    owner: root
    mode: 0700
  when: ansible_distribution == "CentOS"

- name: add systemd service unit to disable THP
  copy:
    src: disable_transparent_hugepages.service
    dest: /lib/systemd/system/disable_transparent_hugepages.service
    owner: root
    mode: 0700
  when: ansible_distribution == "Debian"

- name: enable systemd service unit to disable THP
  service:
    name: disable_transparent_hugepages.service
    enabled: yes
    state: started
