---
# tasks file for role
- name:  service {{name}} {{state}}
  service:
    name: "{{name}}"
    state: "{{state}}"

- name: Wait until service is open
  wait_for:
    host: "{{ansible_hostname}}"
    port: "{{port_check}}"
    timeout: 30
  when: port_check is defined
