---
- name: Install vitam-mongos package
  package:
    name: vitam-mongos
    state: latest
  notify:
    - restart mongos

- name: enable mongos
  service:
    name: vitam-mongos
    enabled: true
  notify:
    - restart mongos

#### Configuration ####

- name: Check that the directories exists (must be removed when the RPM plugin will be patched)
  file:
    path: "{{vitam_folder_root}}/{{ item }}/mongos"
    state: directory
    owner: "{{ vitamdb_user}}"
    group: "{{ vitam_group }}"
    mode: "{{ vitam_folder_permission }}"
  with_items:
    - app
    - bin
    - conf
    - data
    - lib
    - log
    - script
    - tmp
  notify:
    - restart mongos

- name: Create the mongos configuration server file
  template:
    src: mongos.conf.j2
    dest: "{{mongo_config_path}}/mongos.conf"
    owner: "{{ vitamdb_user}}"
    mode: "{{vitam_conf_permission}}"
  notify:
    - restart mongos

#### Consul configuration ####

- name: Ensure consul config dir is OK
  file:
    path: "{{consul_folder_conf}}"
    state: directory
    owner: "{{ vitam_user }}"
    group: "{{ vitam_group }}"

- name: Deploy consul agent service declaration
  template:
    src: "service-componentid.json.j2"
    dest: "{{consul_folder_conf}}/service-mongos.json"
    owner: "{{ vitam_user }}"
    group: "{{ vitam_group }}"
    mode: "{{vitam_conf_permission}}"
  notify:
   - reload consul configuration

# Ensure that the installation is complete and consul up before contnuing...
- meta: flush_handlers

- name: Ensure service is started
  service:
    name: vitam-mongos
    state: started

#### Mongo online configuration ####
# Note : mongodb needs to be started for these elements to succeed

# Enable mongo passphrase

- name: Copy the passphrase
  template:
    src: "keyfile.j2"
    dest: "{{ mongo_config_path }}/keyfile"
    owner: "{{ vitamdb_user}}"
    group: "{{vitam_group}}"
    mode: 0600
