---
# Installation order
#
#   1. Normalize
# 	2. Consul
#	3. Elasticsearch Log
#	4. Log server
#	5. rsyslog
#	6. Elasticsearch Data
#	7. Mongo
#	8. Vitam applications

### HOSTS NORMALIZATION ###
- hosts: vitam
  roles:
    - normalize-host

### CONSUL INSTALLATION ###
# KWA : TODO : installer les serveurs en serial 1 avant les agents (qui n'en ont pas besoin, du serial 1)
- hosts: vitam
  serial: 1
  roles:
    - consul

### ELASTICSEARCH LOG INSTALLATION ###
- hosts: hosts-elasticsearch-log
  roles:
    - {role: elasticsearch-cluster, port_http: "{{elasticsearch_log_http_port}}", port_tcp: "{{elasticsearch_log_tcp_port}}", groupe: log }

### LOG SERVER INSTALLATION ###
- hosts: hosts-log-server
  roles:
    - {role: log-server, cluster_name: elasticsearch-log}

### RSYSLOG INSTALLATION ###
# Vitam solution deployment
# TODO : à régler properment
- hosts: vitam
  roles:
    - rsyslog

### ELASTICSEARCH DATA INSTALLATION ###
- hosts: hosts-elasticsearch-data
  roles:
    - {role: elasticsearch-cluster, port_http: "{{elasticsearch_data_http_port}}", port_tcp: "{{elasticsearch_data_tcp_port}}", groupe: data }

### MONGO DB INSTALLATION ###

# mongodb commons (yum install, etc...)
- hosts: mongo_common
  roles:
  - role: mongo_common

# Mongoc replicas configuration
- hosts: mongoc
  roles:
    - {role: mongoc, mongo_bin: mongod}

# Mongod replicas configuration
- hosts: mongod
  roles:
    - {role: mongod, mongo_bin: mongod, shard_id: 0}

# Mongos configuration
- hosts: mongos
  roles:
    - {role: mongos, mongo_bin: mongos}

# Mongo cluster configuration, database & users declaration
- hosts: mongos
  roles:
    - {role: mongo_configure, shard_id: 0}

- hosts: hosts-mongoclient
  roles:
   - role: mongoclient
     # define mongoclient_user & mongoclient_pwd to enable http authentication
#     mongoclient_user: "{{mongoClientUser}}"
#     mongoclient_pwd: "{{mongoClientPassword}}"
     mongoclient_root_url: "http://{{ansible_hostname}}{{ mongoclientbaseUrl }}"
     mongoclient_port: "{{mongoclientPort}}"
     mongoclient_confdb:
       host: "{{vitam_mongodb_host}}"
       port: "{{mongos_port}}"
       name: "{{mongoclientDbName}}"
       user: "{{mongoClientUser}}"
       pwd: "{{mongoClientPassword}}"
# # MongoDB installation
# - hosts: hosts-mongodb
#   roles:
#     - mongodb


## VITAM ###################################################################################""

- hosts: hosts-storage-offer-default
  roles:
    - {role: vitam, vitam_component: storage-offer-default, java_args: /vitam/conf/storage-offer-default/default-offer.conf, port_http: "{{vitam_storageofferdefault_port}}", port_https: "{{vitam_storageofferdefault_port_https}}", tls_active: true, secret_platform: "true", password_keystore: "{{keystores.server.storage_offer_default}}", password_manager_keystore: "{{keystores.server.storage_offer_default}}", password_truststore: "{{truststores.client_storage}}", password_grantedstore: "{{grantedstores.client_storage}}", vitam_certificate_client_type: "storage" }

- hosts: hosts-storage-engine
  roles:
    - {role: vitam, vitam_component: storage, java_args: /vitam/conf/storage/storage-engine.conf, port_http: "{{vitam_storageengine_port}}", secret_platform: "true", vitam_certificate_client_type: "storage" }
    - storage

- hosts: hosts-metadata
  roles:
    - {role: vitam, vitam_component: metadata, java_args: /vitam/conf/metadata/metadata.conf, port_http: "{{vitam_metadata_port}}", cluster_name: elasticsearch-data, secret_platform: "true" }

- hosts: hosts-logbook
  roles:
    - {role: vitam, vitam_component: logbook, java_args: /vitam/conf/logbook/logbook.conf, port_http: "{{vitam_logbook_port}}", cluster_name: elasticsearch-data, secret_platform: "true" }
    - logbook_secure_operations

- hosts: hosts-functional-administration
  roles:
    - {role: vitam, vitam_component: functional-administration, java_args: /vitam/conf/functional-administration/functional-administration.conf, port_http: "{{vitam_functional_administration_port}}", secret_platform: "true", cluster_name: elasticsearch-data }

- hosts: hosts-workspace
  roles:
    - {role: vitam, vitam_component: workspace ,java_args: /vitam/conf/workspace/workspace.conf, port_http: "{{vitam_workspace_port}}", secret_platform: "true" }

- hosts: hosts-processing
  roles:
    - {role: vitam, vitam_component: processing,java_args: /vitam/conf/processing/processing.conf, port_http: "{{vitam_processing_port}}", secret_platform: "true" }

- hosts: hosts-worker
  roles:
    - siegfried
    - {role: vitam, vitam_component: worker,java_args: /vitam/conf/worker/worker.conf, port_http: "{{vitam_worker_port}}", secret_platform: "true" }

- hosts: hosts-access-internal
  roles:
    - {role: vitam, vitam_component: access-internal, java_args: /vitam/conf/access-internal/access-internal.conf, port_http: "{{vitam_accessinternal_port}}", secret_platform: "true" }

- hosts: hosts-access-external
  roles:
    - {role: vitam, vitam_component: access-external, java_args: /vitam/conf/access-external/access-external.conf, port_http: "{{vitam_accessexternal_port}}", port_https: "{{vitam_accessexternal_port_https}}", tls_active: true, secret_platform: "false", password_keystore: "{{keystores.server.access_external}}", password_manager_keystore: "{{keystores.server.access_external}}", password_truststore: "{{truststores.client_external}}", password_grantedstore: "{{grantedstores.client_external}}", vitam_certificate_client_type: "external" }

- hosts: hosts-ingest-internal
  roles:
    - {role: vitam, vitam_component: ingest-internal, java_args: /vitam/conf/ingest-internal/ingest-internal.conf, port_http: "{{vitam_ingestinternal_port}}", secret_platform: "true" }

- hosts: hosts-ingest-external
  roles:
    - siegfried
    - {role: vitam, vitam_component: ingest-external, java_args: /vitam/conf/ingest-external/ingest-external.conf, port_http: "{{vitam_ingestexternal_port}}", port_https: "{{vitam_ingestexternal_port_https}}", tls_active: true, secret_platform: "false", password_keystore: "{{keystores.server.ingest_external}}", password_manager_keystore: "{{keystores.server.ingest_external}}", password_truststore: "{{truststores.client_external}}", password_grantedstore: "{{grantedstores.client_external}}", vitam_certificate_client_type: "external" }
    - {role: clamav, when: installation_clamav=="true"}

- hosts: hosts-ihm-demo
  roles:
    - {role: vitam, vitam_component: ihm-demo, java_args: /vitam/conf/ihm-demo/ihm-demo.conf, port_http: "{{vitam_ihm_demo_port}}", secret_platform: "false", vitam_certificate_client_type: "external" }
    - ihm-demo-front
