---

- name: install siegfried package
  package:
    name: vitam-siegfried
    state: latest
  notify:
    - restart siegfried

- name: Ensure siegfried is started on boot
  service:
    name: vitam-siegfried
    enabled: true
  notify:
    - restart siegfried

- name: Ensure service is started
  service:
    name: "vitam-siegfried"
    state: started
