---

# TODO: try replace sed by: |openssl rsa -inform PEM -outform PEM [-pubout]
# Best way to do that is to use openssl rsa but after it the certificate headers are missing
# We should investigate more on this subject as sed should not be used for that...
- name: extract certificate
  shell: "openssl pkcs12 -nodes -in /etc/{{apache_service}}/certs/keystore_client_{{environnement}}.p12 -passin pass:'{{keystores.client_external.reverse}}' -out /etc/{{apache_service}}/certs/keystore_client_{{environnement}}.pem && sed -i 's/ PRIVATE KEY/ RSA PRIVATE KEY/g' /etc/{{apache_service}}/certs/keystore_client_{{environnement}}.pem"

- name: set certificate attributes
  file:
    path: "/etc/{{apache_service}}/certs/keystore_client_{{environnement}}.pem"
    owner: "root"
    mode: 0400

- name: reload apache
  service:
    name: "{{apache_service}}"
    state: "reloaded"
