---

# Check SELinux with command line instead of using ansible facts since we may not have libselinux-python
- name: Get selinux mode
  shell: which getenforce > /dev/null 2>&1;if [ $? != 0 ]; then echo "Not installed"; else getenforce; fi
  register: selinux

- name: Check that selinux is not set to enforcing
  fail: msg="selinux detected and looks like to be set to enforcing mode, please set selinux to permissive or disabled."
  when: (selinux.stdout == "Enforcing" )

- name: Ensure parent dir is OK ith correct permissions
  file:
    path: "{{vitam_folder_root}}"
    state: directory
    owner: root
    group: root
    mode: 0555

- name: Ensure {{vitam_folder_root}} sub-directories exist
  file:
    path: "{{vitam_folder_root}}/{{item}}"
    owner: root
    group: root
    state: directory
    mode: 0555
  with_items:
    - app
    - bin
    - conf
    - data
    - lib
    - log
    - script
    - tmp

- block:
  - name: Install epel-release repository
    package:
      name: epel-release
      state: present

  - name: Update yum cache
    shell: "yum clean all && yum --disablerepo='*' --enablerepo='local, vitam-*' makecache" 
    tags:
      - update_package_vitam
  
  when: ansible_distribution == "CentOS"
  # KWA review : Vérifier la présence des backports Jessie ?

 

- block:
  - name: check jessie-backports repo are present
    apt_repository:
      repo: "{{item}}"
      state: present
    with_items:
      - "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
      - "deb-src http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"

  # - name: Update apt cache
  #   shell: "apt-get clean && apt-get update"
  #   tags:
  #     - update_package_vitam
  
  - name: run apt-update
    apt:
      update_cache: yes
    tags:
      - update_package_vitam

  when: ansible_distribution == "Debian"